### ISSUE TITLE
Allow list of variable names in retriever config file

### ISSUE THREAD

**Issue by maxwelllevin** [tsdat/tsdat#129]
It would be nice if the `retriever.yaml` file allowed users to specify multiple variable names for the same retrieval rule group. E.g.,

**in retriever.yaml**:

```yaml
coords:
  time:
    .*:
      # name: timestamp # <--- current
      name: [time, timestamp]  # <--- proposed
      data_converters:
        - classname: tsdat.io.converters.StringToDatetime
          format: "%Y-%m-%d %H:%M:%S"
          timezone: UTC
```

The `name` field should be allowed to be either a list of input variable names or a single string with the variable name (preserve existing syntax)

Use case: @jmcvey3 is working with some data where the field names changed at some point in time, but the filenames are identical so regex cannot be used to differentiate which retrieval rule to use. This feature would support that work
