### ISSUE TITLE
Allow relative paths in pipeline config file

### ISSUE THREAD

**Issue by maxwelllevin** [tsdat/tsdat#174]
I think it'd make sense to allow relative paths in the pipeline config files. The current format is like this:

```yaml
# pipeline_sa1.yaml
classname: pipelines.ld.disdrometer.pipeline.LidarDisdrometer
triggers: [.*sa1.ld.z02.*\.dat]
retriever:
  path: pipelines/ld/disdrometer/config/retriever.yaml
dataset:
  path: pipelines/ld/disdrometer/config/dataset.yaml
  overrides:
    /attrs/location_id: sa1
    /attrs/z_id: z02
quality:
  path: shared/quality.yaml
storage:
  path: shared/storage.yaml
```

Proposed refactoring
```yaml
# pipeline_sa1.yaml
classname: pipelines.ld.disdrometer.pipeline.LidarDisdrometer
triggers: [.*sa1.ld.z02.*\.dat]
retriever:
  path: ./retriever.yaml
dataset:
  path: ./dataset.yaml
  overrides:
    /attrs/location_id: sa1
    /attrs/z_id: z02
quality:
  path: shared/quality.yaml
storage:
  path: shared/storage.yaml
```

Starting with a `./` or `../` would make `tsdat` use a path relative to the pipeline config file, while starting with any other character would treat it as relative to the project root.

Considering something similar with the `classname` property, but I understand less about how that works. E.g., I'd like to do `classname: pipeline.LidarDisdrometer` to refer to the `LidarDisdrometer` class in `./pipeline.py`, but I'd also still want to allow things like `classname: tsdat.IngestPipeline`. Maybe this just means adding the current pipeline folder to the `sys.path`?
