### ISSUE TITLE
Error running example pipeline

### ISSUE THREAD

**Issue by jmcvey3** [tsdat/tsdat#3]
Simply followed the download and template instructions in the documentation to get this one. Testing the pipeline will also throw this error.

It's some sort of issue where `time` is read in from the "config.yml" file, but not actually stored in the file dataset. It appears the variable is in fact created within the `DatasetDefinition` object and is stored with `height` as coordinates, butmakes it no further. There are a couple 'is_required' sanity checks it appears to get past too without throwing a warning, but I'm not familiar enough with the code.

We've gotten the pipeline running for tide guage data, though with a slightly-customized csv filehandler to deal the particularities of the instrument's output format, and don't have this issue. 
I've had issues with xarray not creating data-arrays from numbers it didn't like (something with the dimension order not matching up, i.e [1, #] vs [#, 1] vs [#, ] etc), not sure if this is related.

I'm using a brand-spanking new version of Anaconda that I installed last Friday after breaking conda on an unrelated project.

`Traceback (most recent call last):`

`  File "C:\Users\mcve343\Anaconda3\lib\site-packages\xarray\core\dataset.py", line 1371, in _construct_dataarray
    variable = self._variables[name]`

`KeyError: 'time'`

`During handling of the above exception, another exception occurred:`

`Traceback (most recent call last):`

`  File "C:\Users\...\tsdat-mcrl-local\run_pipeline.py", line 37, in <module>
    main()`

`  File "C:\Users\...\tsdat-mcrl-local\run_pipeline.py", line 33, in main
    run_pipeline(mode=args.mode, input_files=files)`

`  File "C:\Users\...\tsdat-mcrl-local\pipeline\runner.py", line 37, in run_pipeline
    pipeline.run(path)`

`  File "C:\Users\...\Anaconda3\lib\site-packages\tsdat\pipeline\ingest_pipeline.py", line 35, in run
    dataset = self.standardize_dataset(raw_dataset_mapping)`

`  File "C:\Users\...\Anaconda3\lib\site-packages\tsdat\pipeline\pipeline.py", line 85, in standardize_dataset
    merged_dataset = self.add_missing_variables(merged_dataset, definition)`

`  File "C:\Users\...\Anaconda3\lib\site-packages\tsdat\pipeline\pipeline.py", line 152, in add_missing_variables
    shape = [len(dataset[dim_name]) for dim_name in var_def.dims.keys()]`

`  File "C:\Users\...\Anaconda3\lib\site-packages\tsdat\pipeline\pipeline.py", line 152, in <listcomp>
    shape = [len(dataset[dim_name]) for dim_name in var_def.dims.keys()]`

`  File "C:\Users\...\Anaconda3\lib\site-packages\xarray\core\dataset.py", line 1475, in __getitem__
    return self._construct_dataarray(key)`

`  File "C:\Users\...\Anaconda3\lib\site-packages\xarray\core\dataset.py", line 1373, in _construct_dataarray
    _, name, variable = _get_virtual_variable(`

`  File "C:\Users\...\Anaconda3\lib\site-packages\xarray\core\dataset.py", line 169, in _get_virtual_variable
    ref_var = variables[ref_name]`

`KeyError: 'time'`

**Comment by maxwellevin** [comment]
Hi @jmcvey3 , thanks for opening this issue. Could you provide an example I can run to reproduce this error? Your stack trace references `tsdat-mcrl-local`, which I'm guessing is a private repo of yours. I wasn't able to reproduce this using the out-of-the-box local ingest template repo with a fresh conda install and python 3.7.4 (I also tried python 3.8.10).

One curious thing about this error is that it is occurring in the `self.standardize_dataset()` part of the `IngestPipeline.run()` method. The dataset standardization occurs after the raw dataset(s) are saved to the storage area, and the `'time'` variable is needed in order to build the raw filenames. So the fact that it crashed only at this stage means that the pipeline was able to read the time variable from your raw dataset, but not from the dataset being standardized. I'm not sure how that could be.

**Comment by jmcvey3** [comment]
Hi @maxwellevin, interesting, because it does come up from using the out-of-the-box template repo and trying to run the morro bay data. A couple co-workers had the same issue but had difficulty tracing it back as well, though the error didn't come up using our own tide gauge .csv data.

Yes, I traced the issue into `reduce_raw_datasets()` to the `for variable in definition.vars.values():` loop, line 250 in `pipeline.py`. That loop populates the `retrieval rules` dict, so if that loop returns nothing to that dict, no variables are transferred off of the raw dataset(s), and this error comes up. 
To get that loop to return something, `variable.has_input()` must return `True`, a.k.a. the config.yml file requires 'input: \ name: ' lines for every variable in the raw datafile, with 'name' corresponding to the variable name in the raw datafile. So I'm pretty sure it's a config file problem.
However, that lidar datafile has that weird thing with the altitude specified before each name, so I'm lost on how that works here.

**Comment by jmcvey3** [comment]
Let me know if you still can't replicate this issue, but changing line 250 in `pipeline.py` to the following solves it for me:
        
        #for variable in definition.vars.values():
        def_all = definition.vars.copy()
        def_all.update(definition.coords)
        for variable in def_all.values():

**Comment by maxwellevin** [comment]
Hi @jmcvey3, sorry for the radio silence; I have been very busy with another project. Getting back to this now.

**Comment by maxwellevin** [comment]
@jmcvey3 I was able to produce a somewhat similar-looking error by downgrading the version of tsdat to 0.2.0 (latest at time of writing is 0.2.4). It's still not quite the same as what you get, but it make me realize that I never asked what version of python/tsdat/dependencies you were using. It is also helpful to know when you made your template repository.

If you were not using tsdat v0.2.4, could you install it and let me know if you still get the same error without using the workaround you posted earlier?

**Comment by jmcvey3** [comment]
I added the yml file. I can only produce this error with the lidar datafile provided, I can't make it happen with the other datafiles I'm working with that use similar config files. I did uninstall tsdat completely for sanity's sake.

`conda create --name tsdat-dev python=3.8`
`conda activate tsdat-dev`
`cd <tsdat-local>`
`pip install -r requirements.txt`
`python run_pipeline.py data/inputs --mode dev`  to produce the error
`conda env export > environment_issue3.yml`

[environment_issue3.zip](https://github.com/tsdat/tsdat/files/6909693/environment_issue3.zip)

**Comment by maxwellevin** [comment]
I had to modify your environment.yml file due to several windows-specific dependencies that don't exist for MacOS. Conda also had trouble with several of the dependencies, so I had to remove the commit reference leaving just the version number. I was again unable to replicate the error you are getting. 

`environment.yml`:
```yaml
name: tsdat-dev
channels:
  - defaults
dependencies:
  - ca-certificates=2021.7.5
  - certifi=2021.5.30
  - openssl=1.1.1k
  - pip=21.1.3
  - python=3.8.10
  - setuptools=52.0.0
  - sqlite=3.36.0
  # - vc=14.2=h21ff451_1
  # - vs2015_runtime=14.27.29016=h5e58377_2
  - wheel=0.36.2
  # - wincertstore=0.2=py38_0
  - pip:
    - act-atmos==1.0.4
    - backcall==0.2.0
    - boto3==1.18.11
    - botocore==1.21.11
    - cftime==1.5.0
    - cfunits==3.3.3
    - charset-normalizer==2.0.3
    - click==8.0.1
    - cloudpickle==1.6.0
    - cmocean==2.0
    - colorama==0.4.4
    - cycler==0.10.0
    - dask==2021.7.1
    - debugpy==1.4.1
    - decorator==5.0.9
    - distributed==2021.7.1
    - fsspec==2021.7.0
    - heapdict==1.0.1
    - idna==3.2
    - ipykernel==6.0.3
    - ipython==7.25.0
    - ipython-genutils==0.2.0
    - jedi==0.18.0
    - jmespath==0.10.0
    - jplephem==2.16
    - jupyter-client==6.1.12
    - jupyter-core==4.7.1
    - kiwisolver==1.3.1
    - locket==0.2.1
    - matplotlib==3.4.2
    - matplotlib-inline==0.1.2
    - msgpack==1.0.2
    - netcdf4==1.5.7
    - numpy==1.21.1
    - packaging==21.0
    - pandas==1.3.1
    - parso==0.8.2
    - partd==1.2.0
    - pathspec==0.9.0
    - pickleshare==0.7.5
    - pillow==8.3.1
    - pint==0.17
    - prompt-toolkit==3.0.19
    - psutil==5.8.0
    - pygments==2.9.0
    - pyparsing==2.4.7
    - pyproj==3.1.0
    - python-dateutil==2.8.2
    - pytz==2021.1
    # - pywin32==301
    - pyyaml==5.4.1
    - pyzmq==22.1.0
    - requests==2.26.0
    - s3transfer==0.5.0
    - scipy==1.7.0
    - seaborn==0.11.1
    - sgp4==2.20
    - six==1.16.0
    - skyfield==1.39
    - sortedcontainers==2.4.0
    - tblib==1.7.0
    - toolz==0.11.1
    - tornado==6.1
    - traitlets==5.0.5
    - tsdat==0.2.4
    - urllib3==1.26.6
    - wcwidth==0.2.5
    - xarray==0.19.0
    - yamllint==1.26.1
    - zict==2.0.0
```

Steps I took:
```
$ git clone https://github.com/tsdat/ingest-template-local.git
$ cd ingest-template-local
$ conda env create --name tsdat-dev --file=environment.yml
$ conda activate tsdat-dev
(tsdat-dev) $ python run_pipeline.py data/inputs --mode dev
```

Since I am using the same versions of the same packages you are it would appear that the error is due to some underlying operating system difference. We saw something similar to this in #4, where the `datetime` module on Windows was not able to import one of its internal modules.
