### ISSUE TITLE
Data types are not set correctly

### ISSUE THREAD

**Issue by maxwelllevin** [tsdat/tsdat#93]
**Describe the bug**
The data types assigned to variables in the `dataset.yml` configuration file does not stick; the data types in the output are not guaranteed to match the data type specified.

**To Reproduce**
Minimal set of steps to reproduce the behavior:
1. Clone the pipeline-template
2. Run the included example

In the `dataset.yml` file:
```yaml
  num_zero_crossings:
    dims: [time]
    dtype: int
    attrs:
      long_name: Number of Zero Crossings
      units: "1"
      _FillValue: -9999
```

In the output dataset:
<img width="685" alt="image" src="https://user-images.githubusercontent.com/24307537/173699089-3cf871f6-4eec-45c5-a565-5357099e66da.png">

**Expected behavior**
The output data type should match the specified data type in the configuration file.

In this case I would expect `int64` or something similar since the exact type of `int` was not specified in the dataset configuration file.
